name: Build and Release Isk App.

on:
  push:
    branches:
      - main
      - deployer

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Get version from package.json
        id: get_version
        shell: pwsh
        run: |
          $version = (Get-Content package.json | ConvertFrom-Json).version
          echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Install dependencies
        run: npm ci

      - name: Publish
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{GITHUB.TOKEN}}
