name: Build and Release Isk App.

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    env:
      VERSION: ${{ github.ref_name }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build frontend (Vite)
        run: npm run build

      - name: Install electron-builder dependencies
        run: npx electron-builder install-app-deps

      - name: Build Electron app installer
        run: npm run dist
        env: 
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: List dist directory
        run: dir dist

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          token: ${{ secrets.PAT_TOKEN }}

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "dist/eve-isk-management Setup ${{ env.VERSION }}.exe"
          asset_name: "eve-isk-management Setup ${{ env.VERSION }}.exe"
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
